const opList = [
    'a o',
    'abdullah',
    'absalom',
    'acilia',
    'adele',
    'aggie 68',
    'agotogi',
    'agsilly',
    'agyo',
    'ahhoesunen ix',
    'ahho zurako',
    'ahiru',
    'aisa',
    'akehende',
    'akudai kanzaburo',
    'akumai',
    'aladine',
    'albion',
    'ally',
    'alpacaman',
    'alvida',
    'amadob',
    'amazon',
    'an zengaiina',
    'and',
    'andre',
    'anjo',
    'ankoro',
    'antonio',
    'aphelandra',
    'aremo ganmi',
    'arlong',
    'arrow',
    'arthur',
    'aruyutayan v',
    'asahija',
    'asashichi',
    'ashuraoji',
    'aswa',
    'atagoyama',
    'atmos',
    'attach',
    'avalo pizarro',
    'azuki',
    'babanuki',
    'babe',
    'baby 5',
    'bacura',
    'baggaley',
    'bakezo',
    'bakkin',
    'banedessinée',
    'banchi',
    'banchina',
    'bankuro',
    'banshee',
    'banzaburo',
    'bao',
    'bao huang',
    'bariete',
    'barrel',
    'barry',
    'bartholomew kuma',
    'bartolomeo',
    'bas',
    'basil hawkins',
    'basilisk',
    'bastille',
    'batchee',
    'batman',
    'baxcon',
    'beer vi',
    'belo betty',
    'belladonna',
    'bellamy',
    'bellett',
    'bell-mère',
    'benn beckman',
    'bentham',
    'bepo',
    'bian',
    'big pan',
    'bimine',
    'bingo',
    'bishamon',
    'biyo',
    'bizarre',
    'black maria',
    'blackback',
    'blamenco',
    'blenheim',
    'blondie',
    'blue fan',
    'blue gilly',
    'bluejam',
    'blueno',
    'blumarine',
    'boa hancock',
    'boa marigold',
    'boa sandersonia',
    'bobbin',
    'bobby funk',
    'bobomba',
    'bogard',
    'bomba',
    'bomba',
    'bongo',
    'bonk punch',
    'boo',
    'boodle',
    'borsalino',
    'bourbon jr,',
    'braham',
    'brahm',
    'brannew',
    'brew',
    'briscola',
    'brocca',
    'brogy',
    'brontosaurus',
    'brook',
    'buche',
    'buchi',
    'buffalo',
    'buggy',
    'buhichuck',
    'building snake',
    'bunbuku',
    'bungo',
    'bunny joe',
    'bushon',
    'busshiri',
    'byron',
    'cabaji',
    'caesar clown',
    'caimanlady',
    'camie',
    'camel',
    'cancer',
    'candre',
    'cands',
    'candy',
    'capone bege',
    'capone pez',
    'capote',
    'caribou',
    'carmel',
    'carne',
    'carrot',
    'catacombo',
    'catarinaevon',
    'cavendish',
    'cb gallant',
    'cerberus',
    'cezar',
    'chabo',
    'chadros higelyges',
    'chaka',
    'chao',
    'chap',
    'chappe',
    'charlos',
    'akimeg',
    'allmeg',
    'amande',
    'anana',
    'angel',
    'anglais',
    'basans',
    'basskarte',
    'bavarois',
    'brownie',
    'broyé',
    'brulee',
    'cabaletta',
    'cadenza',
    'chiboust',
    'chiffon',
    'cinnamon',
    'citron',
    'compo',
    'compote',
    'cornstarch',
    'counter',
    'cracker',
    'custard',
    'acquoise',
    'daifuku',
    'e-chat',
    'olce',
    'osmarche',
    'ragée',
    'effilée',
    'flampe',
    'fuyumeg',
    'gala',
    'galette',
    'hachée',
    'harumeg',
    'high-fat',
    'joconde',
    'joscarpone',
    'kanten',
    'katakuri',
    'kato',
    'laurin',
    'linlin',
    'lola',
    'maple',
    'marble',
    'marnier',
    'mascarpone',
    'mash',
    'melise',
    'mobile',
    'mondée',
    'mont-dor',
    'montb',
    'moscato',
    'mozart',
    'myukuru',
    'newgo',
    'newichi',
    'newji',
    'newsan',
    'newshi',
    'noisette',
    'normande',
    'nougat',
    'nusstorte',
    'nutmeg',
    'opera',
    'oven',
    'panna',
    'perospero',
    'poire',
    'praline',
    'prim',
    'pudding',
    'raisin',
    'saint-marc',
    'smoothie',
    'snack',
    'tablet',
    'wafers',
    'wiro',
    'yuen',
    'zuccotto',
    'chess',
    'chesskippa',
    'chew',
    'chichilisia',
    'chicken',
    'chimney',
    'chinjao',
    'chihaya',
    'chiya',
    'cho',
    'chocho',
    'chocolat',
    'choi',
    'chome',
    'chouchou',
    'chuchun',
    'chuji',
    'clione',
    'clover',
    'coburn',
    'cocoa',
    'cocox',
    'colscon',
    'columbus',
    'comil',
    'concelot',
    'conis',
    'corgi',
    'coribou',
    'cornelia',
    'cosette',
    'cosmo',
    'cosmos',
    'cotton',
    'couran',
    'cowboy',
    'crocodile',
    'crocus',
    'curiel',
    'curlyadan',
    'dachoman',
    'daddyee',
    'dagama',
    'daidalos',
    'daifugo',
    'daigin',
    'daikoku',
    'daikon',
    'daisy',
    'dalmatian',
    'dalton',
    'damask',
    'daruma',
    'daz bonez',
    'decalvan brothers',
    'delacuaji',
    'dellinger',
    'demaro black',
    'den',
    'denjiro',
    'devilias',
    'diamante',
    'didit',
    'diesel',
    'diez barrels',
    'dirt boss',
    'disco',
    'dobby ibadonbo',
    'doberman',
    'dobon',
    'doc q',
    'dogra',
    'dogya',
    'doha ittanka ii',
    'doma',
    'domino',
    'domo-kun',
    'donannoyo',
    'donovan',
    'donquino',
    'doflamingo',
    'homing',
    'mjosgard',
    'rosinante',
    'doran',
    'doringo',
    'dorry',
    'dosun',
    'dotaku',
    'dracule mihawk',
    'dragon 13',
    'draw',
    'drip',
    'drophy',
    'drug peclo',
    'du feld',
    'ducky bree',
    'duval',
    'eddy',
    'edward newgate',
    'edward weevil',
    'eiri',
    'egana',
    'eggplant soldier',
    'elizabello 2',
    'elmy',
    'emporio ivankov',
    'enel',
    'enishida',
    'epoida',
    'époni',
    'erik',
    'erio',
    'esta',
    'eustass kid',
    'farafra',
    'farul',
    'faust',
    'fen bock',
    'finamore',
    'fillonce',
    'fishbonen',
    'fisher tiger',
    'flapper',
    'forest boss',
    'forliewbs',
    'fossa',
    'fourtricks',
    'foxy',
    'francois',
    'franky',
    'fuga',
    'fugetsu omusubi',
    'fujin',
    'fukaboshi',
    'fukurokuju',
    'fukurou',
    'fullbody',
    'funkfreed',
    'furrari',
    'fuza',
    'gaburu',
    'gaimon',
    'gal',
    'galaxy',
    'galdino',
    'gally',
    'gama pyonnosuke',
    'gambia',
    'gan fall',
    'gancho',
    'ganryu',
    'ganryu',
    'gatherine',
    'gatz',
    'gazelleman',
    'gecko moria',
    'gedatsu',
    'gem',
    'genbo',
    'genrin',
    'genzo',
    'george black',
    'george mach',
    'gerd',
    'giberson',
    'gimlet',
    'gin',
    'gina',
    'ginko',
    'ginnosuke',
    'ginrummy',
    'giro chintaro',
    'giolla',
    'gion',
    'giovanni',
    'gladius',
    'glove',
    'gode',
    'going merry',
    'goki',
    'gol, roger',
    'goldberg',
    'goldfish princess',
    'gomorrah',
    'gonbe',
    'goo',
    'gorilla',
    'gorishiro',
    'goro',
    'gorobe',
    'gotti',
    'grabar',
    'gram',
    'great michael',
    'gyaro',
    'gyoro',
    'gyoru',
    'gyro',
    'hack',
    'hack',
    'hajrudin',
    'hakowan',
    'ham burger',
    'hamburg',
    'hamlet',
    'hammond',
    'han',
    'hana',
    'hangan',
    'hanger',
    'hanji',
    'hannyabal',
    'hanzo',
    'happa yamao',
    'happygun',
    'hara',
    'haredas',
    'harisenbon',
    'haritsu kendiyo',
    'haruta',
    'hasami',
    'hatcha',
    'hatchan',
    'hattori',
    'heat',
    'helmeppo',
    'heppoko',
    'hera',
    'hera',
    'heracles',
    'herb',
    'hewitt',
    'hidayu',
    'hideo usaguchi',
    'higuma',
    'hihimaru',
    'hikoichi',
    'hildon',
    'hina',
    'hippo gentleman',
    'hiramera',
    'hiriluk',
    'hiroshi',
    'hitsugisukan',
    'ho',
    'hocha',
    'hocker',
    'hody jones',
    'hoe',
    'hogback',
    'hoichael',
    'holedem',
    'holy',
    'home',
    'hongo',
    'honner',
    'hotei',
    'hotori',
    'howling gab',
    'hublot',
    'humphrey',
    'hustle',
    'hyogoro',
    'hyota',
    'hyoutauros',
    'hyouzou',
    'ibiributsu',
    'ibusu',
    'iceburg',
    'ichika',
    'ichiro kumaguchi',
    'ideaman',
    'ideo',
    'igaram',
    'ikaros much',
    'ikkaku',
    'ikkaku',
    'im',
    'inazuma',
    'inbi',
    'indigo',
    'inhel',
    'inoichibannosuke',
    'inuarashi',
    'inukai',
    'inuppe',
    'ipponmatsu',
    'ipponume',
    'isa',
    'ishigo shitemanna',
    'ishilly',
    'island eater',
    'islewan',
    'issho',
    'isuka',
    'itomimizu',
    'ivan x',
    'izou',
    'iwatobi',
    'jabra',
    'jack',
    'jacksonbanner',
    'saul',
    'jaki',
    'jalmack',
    'jango',
    'jarul',
    'jean ango',
    'jean bart',
    'jean goen',
    'jeep',
    'jeet',
    'jerry',
    'jero',
    'jesus burgess',
    'jew wall',
    'jewelry bonney',
    'jibuemon',
    'jigoku benten',
    'jigoro',
    'jigra',
    'jinbe',
    'jo',
    'jobo',
    'john',
    'john giant',
    'johnny',
    'jorge',
    'jorul',
    'joy boy',
    'jozu',
    'judy',
    'jujiro',
    'juki',
    'julius',
    'junan',
    'kabu',
    'kadar',
    'kagero',
    'kagikko',
    'kaidou',
    'kairen',
    'kairiken',
    'kairo kureyo',
    'kaku',
    'kaku',
    'kakukaku',
    'kakunoshin',
    'kalgara',
    'kalifa',
    'kamakiri',
    'kamekichi',
    'kamijiro',
    'kaneshiro',
    'kanezenny',
    'kappa',
    'karasu',
    'karma',
    'karoo',
    'kasa',
    'kasagoba',
    'kashii',
    'kashigami',
    'katsuzo',
    'kawamatsu',
    'kaya',
    'kazekage',
    'kazenbo',
    'kebi',
    'kechatch',
    'keith',
    'kentauros',
    'kelly funk',
    'kerville',
    'kibagaeru',
    'kibin',
    'kiev',
    'kikipatsu',
    'kiku',
    'kikunojo',
    'kikyo',
    'killer',
    'kimel',
    'kinemon',
    'kinbo',
    'kinderella',
    'king',
    'kingbaum',
    'kinga',
    'kingdew',
    'kinoko',
    'kirinkodanuki',
    'kirintauros',
    'kisegawa',
    'kitton',
    'kiwi',
    'koala',
    'kobe',
    'koby',
    'koda',
    'koito',
    'kojuro',
    'kokoro',
    'komachiyo',
    'komane',
    'konbu',
    'kong',
    'kop',
    'kotatsu',
    'kotetsu',
    'kotori',
    'koushirou',
    'koyama',
    'koza',
    'koze',
    'kozuki hiyori',
    'kozuki momonosuke',
    'kozuki oden',
    'kozuki sukiyaki',
    'kozuki toki',
    'krieg',
    'kuina',
    'kukai',
    'kumadori',
    'kumadori yamanbako',
    'kumae',
    'kumagoro',
    'kumashi',
    'kuni',
    'kunyun',
    'kureha',
    'kuro',
    'kurokoma',
    'kuromarimo',
    'kuroobi',
    'kurosawa',
    'kurotsuru',
    'higurashi',
    'kanjuro',
    'orochi',
    'semimaru',
    'kuzan',
    'kyros',
    'kyuin',
    'kyuji',
    'kyukyu',
    'laboon',
    'lacroix',
    'lacuba',
    'lady tree',
    'laffitte',
    'lao g',
    'laskey',
    'lassoo',
    'lemoncheese',
    'leo',
    'leonero',
    'lily',
    'limejuice',
    'lindbergh',
    'lines',
    'lionbuta',
    'lipoughty',
    'little oars jr,',
    'loki',
    'lola',
    'lord of the coast',
    'louis arnote',
    'lucky roux',
    'lulis',
    'machvise',
    'macro',
    'macro',
    'madilloman',
    'magellan',
    'magra',
    'maha',
    'maidy',
    'maki',
    'makino',
    'makko',
    'mamboshi',
    'mani',
    'manjaro',
    'mansherry',
    'marco',
    'margarita',
    'marguerite',
    'mari',
    'maria napole',
    'marianne',
    'marie',
    'marilyn',
    'marin',
    'mario',
    'teach',
    'marumieta',
    'mash',
    'mashikaku',
    'masira',
    'maskedeuce',
    'massui',
    'master',
    'master of the waters',
    'matryosaka',
    'matryoseka',
    'matryosoka',
    'matryosuka',
    'matsuge',
    'maujii',
    'maynard',
    'max marx',
    'mayushika',
    'mcguy',
    'mckinley',
    'meadows',
    'megalo',
    'mero',
    'merry',
    'michael',
    'mihar',
    'mikazuki',
    'mikio itoo',
    'mikita',
    'milky',
    'millet pine',
    'milo',
    'minatomo',
    'minatomo',
    'minister of the left',
    'minister of the right',
    'minochihuahua',
    'minokoala',
    'minorhinoceros',
    'minoruba',
    'minotaurus',
    'minozebra',
    'misery',
    'miss catherina',
    'miss fathers day',
    'miss friday',
    'miss monday',
    'miss mothers day',
    'miss saturday',
    'miss thursday',
    'miss tuesday',
    'miyagi',
    'mizerka',
    'mizuira',
    'mizuta madaisuki',
    'mizuta mawaritosuki',
    'mocdonald',
    'mocha',
    'mochi',
    'moda',
    'mohji',
    'momonga',
    'momoo',
    'monda',
    'monet',
    'monjii',
    'monjiro',
    'dragon',
    'garp',
    'luffy',
    'monster',
    'mont blanc cricket',
    'mont blanc noland',
    'moodie',
    'moon isaac jr,',
    'moqueca',
    'morgan',
    'morgans',
    'morley',
    'mornin',
    'mororon',
    'motobaro',
    'motzel',
    'mounblutain',
    'mountain god',
    'mountain ricky',
    'mouseman',
    'mousse',
    'moyle',
    'mozambia',
    'mozu',
    'mr 6',
    'mr 7',
    'mr 7',
    'mr 10',
    'mr 9',
    'mr 11',
    'mr 12',
    'mr 13',
    'mr beans',
    'mr love',
    'mr mellow',
    'mr momora',
    'mr shimizu',
    'muchana',
    'mugren',
    'mukkashimi tower',
    'mummy',
    'mummy mee',
    'muret',
    'nako',
    'nami',
    'namur',
    'nangi',
    'napoleon',
    'nashi',
    'natto',
    'nazu ketagari',
    'cobra',
    'titi',
    'vivi',
    'neggy',
    'negikuma maria',
    'nekomamushi',
    'neptune',
    'nerine',
    'nero',
    'nezumi',
    'nico olvia',
    'nico robin',
    'nigeratta',
    'nika',
    'nika',
    'nin',
    'ninjin',
    'ninth',
    'nitro',
    'nnke-kun',
    'noble croc',
    'nokotti',
    'nojiko',
    'nola',
    'nora gitsune',
    'noriko',
    'nosgarl',
    'nubon',
    'nugire yainu',
    'nure-onna',
    'nyasha',
    'nyon',
    'oars',
    'octopako',
    'ochoku',
    'octopus mash',
    'ohm',
    'oide',
    'oimo',
    'okame',
    'okome',
    'omasa',
    'onigumo',
    'onimaru',
    'oran',
    'orlumbus',
    'ossamondo',
    'otohime',
    'outlook iii',
    'packy',
    'pagaya',
    'page one',
    'palms',
    'pandaman',
    'pandawoman',
    'pandora',
    'pankutaakeyan',
    'pansy',
    'pantri',
    'papaneel',
    'pappag',
    'pascia',
    'patty',
    'paulie',
    'pavlik',
    'peachbeard',
    'pearl',
    'peepley lulu',
    'pedro',
    'pekkori',
    'pekoms',
    'pell',
    'pellini',
    'penguin',
    'peppoko',
    'perona',
    'peterman',
    'petermoo',
    'pica',
    'pickles',
    'pierre',
    'piiman',
    'pike',
    'pinky',
    'pisaro',
    'poker',
    'poppoko',
    'poppy',
    'porche',
    'porchemy',
    'poro',
    'ace',
    'rouge',
    'potaufeu',
    'potsun',
    'pound',
    'prometheus',
    'pudding pudding',
    'pudos',
    'puppu',
    'px-1',
    'px-4',
    'px-5',
    'px-7',
    'queen',
    'queen mama chanter',
    'rabbitman',
    'rabiyan',
    'raccoon',
    'raideen',
    'raijin',
    'raizo',
    'raki',
    'rakuda',
    'rakuyo',
    'ramba',
    'ramen',
    'rampo',
    'ran',
    'randolph',
    'rangram',
    'rebecca',
    'reforte',
    'reuder',
    'richie',
    'rika',
    'rikuoldo iii',
    'rindo',
    'rint',
    'ripper',
    'ririka',
    'risky brothers',
    'rivers',
    'road',
    'rob lucci',
    'robson',
    'roche',
    'roche tomson',
    'rock',
    'rocks, xebec',
    'rockstar',
    'roddy',
    'roji',
    'rokkaku',
    'rokki',
    'rolling logan',
    'ronse',
    'zoro',
    'roshio',
    'ross',
    'rosward',
    'rowing',
    'roxanne',
    'run',
    'rush',
    'russian',
    'ryokugyu',
    'ryuboshi',
    'ryunosuke',
    'saber',
    'sabo',
    'sadi',
    'sai',
    'saikoro',
    'sakazuki',
    'saki',
    'saldeath',
    'salome',
    'sam',
    'samosa',
    'samurai batts',
    'sancrin',
    'sandayu',
    'sanji',
    'sanjuan wolf',
    'sanka',
    'sapi',
    'sarahebi',
    'sarfunkel',
    'sarie nantokanette',
    'sarquiss',
    'saru',
    'sarutobi',
    'sasaki',
    'satori',
    'sauce',
    'scarlett',
    'schollzo',
    'scopper gaban',
    'scotch',
    'scotch',
    'scratchmen apoo',
    'seagull guns nozdon',
    'seamars',
    'seira',
    'seki',
    'sengoku',
    'senor pink',
    'sentomaru',
    'serizawa',
    'seto',
    'shachi',
    'shakuyaku',
    'shalria',
    'sham',
    'shanba',
    'shandia chief',
    'shanks',
    'sharinguru',
    'sheepshead',
    'shelly',
    'shiki',
    'kozaburo',
    'ryuma',
    'ushimaru',
    'yasuie',
    'shinetamaruka',
    'shin jaiya',
    'shine',
    'shinobu',
    'shinosuke',
    'shion',
    'shioyaki',
    'shirahoshi',
    'shirutonoruyanaika',
    'shiryu',
    'shishilian',
    'shoujou',
    'shu',
    'shura',
    'shyarly',
    'sicily',
    'silver axe',
    'silvers rayleigh',
    'sind',
    'skull',
    'sleepy',
    'smiley',
    'smoker',
    'smooge',
    'snakeman',
    'sodom',
    'solitaire',
    'some',
    'sonieh',
    'sora',
    'soro',
    'spacey',
    'spandam',
    'spandine',
    'spartan',
    'spector',
    'speed',
    'speed jiru',
    'spencer',
    'sphinx',
    'splash',
    'splatter',
    'spoil',
    'squard',
    'stainless',
    'stalker',
    'stansen',
    'stefan',
    'sterry',
    'stevie',
    'stomp',
    'stool',
    'strawberry',
    'streusen',
    'stroganoff',
    'stronger',
    'stussy',
    'su',
    'sugamichi',
    'sugar',
    'suke',
    'sukoshiba kanishitoru',
    'suleiman',
    'sunbell',
    'surume',
    'sweet pea',
    't bone',
    'tabuhachiro',
    'tacos',
    'takao',
    'take',
    'tama',
    'tama',
    'tamachibi',
    'tamago',
    'tamagon',
    'tamanegi',
    'tank lepanto',
    'tansui',
    'tararan',
    'taro',
    'taroimo',
    'tashigi',
    'tate',
    'tea iv',
    'tegata ringana',
    'tenguyama hitetsu',
    'tenjo-sagari',
    'terracotta',
    'terry',
    'terry gilteo',
    'teru',
    'tetsu',
    'thalassa lucas',
    'thatch',
    'tibany',
    'tilestone',
    'togare',
    'tokijiro',
    'tokikake',
    'toko',
    'tom',
    'tomato gang',
    'tonjit',
    'chopper',
    'tori',
    'toto',
    'toyama tsujigiro',
    'trafalgar, water law',
    'trafalgar lami',
    'trebol',
    'tristan',
    'tritobu',
    'tsugaru umi',
    'tsukimi',
    'tsunagoro',
    'tsunokkov',
    'tsuru',
    'tsurue monnosuke',
    'tsurujo',
    'turco',
    'tyrannosaurus',
    'ubau',
    'ucy',
    'uhho',
    'uholisia',
    'ukkari',
    'ukon',
    'ulti',
    'ultraking',
    'umit',
    'unforgivable mask',
    'uni',
    'unigaro',
    'urashima',
    'urouge',
    'usagihebi',
    'usakkov',
    'usopp',
    'uwattsura',
    'uzu',
    'uzuki tempura',
    'van augur',
    'vanderecken',
    'vanderecken ix',
    'vasco shot',
    'vegapunk',
    'vergo',
    'very good',
    'victoria cindry',
    'ichiji',
    'judge',
    'niji',
    'reiju',
    'sora',
    'yonji',
    'viola',
    'vista',
    'vitan',
    'vito',
    'wadatsumi',
    'wakasa',
    'wallace',
    'wallem',
    'wanda',
    'wany',
    'wanyudo',
    'wanze',
    'wapol',
    'warashi',
    'warazane',
    'waruno furishiro',
    'wellington',
    'wheel',
    'whitey bay',
    'whos-who',
    'wicca',
    'willie gallon',
    'wire',
    'woop slap',
    'wyper',
    'xrake',
    'yama',
    'yamakaji',
    'yamato',
    'yame',
    'yamenahare',
    'yamon',
    'yarisugi',
    'yasopp',
    'yatappe',
    'yazaemon',
    'yokan',
    'yokozuna',
    'yomo',
    'yonka',
    'yonka two',
    'yorki',
    'yosaku',
    'yoshimoto',
    'yotsubane',
    'yu',
    'yui',
    'yuki',
    'yukichi skull',
    'yurikah',
    'zabo',
    'zadie',
    'zala',
    'zambai',
    'zanki',
    'zeff',
    'zeo',
    'zepo',
    'zeus',
    'zodia',
    'zotto',
    'zucca',
    'zunesha',
]
let urls = ["https://static.wikia.nocookie.net/onepiece/images/8/8c/A_O_Anime_Infobox.png", "https://static.wikia.nocookie.net/onepiece/images/f/f1/Abdullah_Anime_Infobox.png"]
let points = 0
let guess = []
let lastGuess = []


// while (points <= 1298) {
const input = document.querySelector("input")
window.addEventListener("keydown", function (e) {
    switch (e.code) {
        case 'Enter':
            guess.push(input.value.toLowerCase())
            if (opList.some(r => guess.includes(r)) && !guess.some(r => lastGuess.includes(r))) {
                const indexThis = guess.toString()
                const indx = opList.indexOf(indexThis)
                const imgUrl = urls[indx]
                const container = document.querySelector("#container")
                const newImg = document.createElement("img")
                newImg.src = `${imgUrl}`
                container.appendChild(newImg)
                points++
                lastGuess.push(...guess)
                guess.pop()
            }
            else if (guess.some(r => lastGuess.includes(r))) {
                alert(`You already guessed ${guess[0]}. Try again`)
                guess.pop()
            }

            else {
                alert(`${guess[0]} Does not exist in the One Piece world. Try again`)
                guess.pop()
            }
            e.preventDefault();
    }
})
    // guess.push(prompt(`Points ${points} Guess OP Character: `).toLowerCase())
// }